name: Testing and Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests and coverage check
        env:
          MONGO_CONNECTION: ${{ secrets.MONGO_CONNECTION }}
          PROJECT_DATABASE: ${{ secrets.PROJECT_DATABASE }}
          PROJECT_COLLECTION: ${{ secrets.PROJECT_COLLECTION}}
          MAX_OFFSET: 2000
        run: |
          ./run_tests.sh